services:
  db:
    image: postgres:17
    container_name: database
    restart: unless-stopped

    environment:
      POSTGRES_USER: max
      POSTGRES_PASSWORD: geheim
      POSTGRES_DB: testdb

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: